### ISSUE TITLE
Error with spring boot 2.1.5

### ISSUE THREAD

**Issue by bogados-zz** [iguissouma/spring-boot-graphql-sqqr#1]
Hey I was looking for your proyect because, generate a graphql from java classes is really useful. 
But, I try to implement your project with Spring boot 2.1.5 and I have an error, with the graphi and different variables, and I cant request for any data from postman.

May be my brains is burned beacause I tried for 2 days to solve it and i could solve it.

If you can help me I will be really grateful with you

Regards,

Sebastian

**Comment by iguissouma** [comment]
Hello,
I simplified the project sample using the spring boot spqr starter.

You can now use the graphql playgound to query the graphql endpoint.
http://localhost:8080/gui

Below an example using a qury with variables:
![Screen Shot 2019-06-24 at 11 11 56 PM](https://user-images.githubusercontent.com/9085108/60052441-909e3a80-96d5-11e9-8ac6-b23af6090115.png)

Please let me know if you have any issue.

**Comment by bogados-zz** [comment]
Thanks.
It's solved
